"""
HydroMoth WAV processor
Processes audio files generated by HydroMoth (https://www.openacousticdevices.info/applications)

Author: Albert Garcia-Benadí (adapted and refactored)
ORCID: 0000-0002-5560-4392
"""

import re
import os
import numpy as np
from datetime import datetime, timezone, timedelta
import calendar
from scipy.io import wavfile


def date2unix(date_obj):
    """Convert datetime to Unix timestamp."""
    return calendar.timegm(date_obj.timetuple())


def unix2date(unix_timestamp):
    """Convert Unix timestamp to datetime."""
    return datetime.utcfromtimestamp(unix_timestamp)


def extract_hydromoth_metadata(wav_path):
    """
    Extract metadata from HydroMoth WAV file header.
    
    Returns:
        dict: Contains timestamp, timezone, battery, temperature, serial_number, etc.
        None: If not a HydroMoth file or metadata cannot be extracted.
    """
    COMMENT_START = 0x38
    COMMENT_LENGTH = 0x180
    
    try:
        with open(wav_path, "rb") as f:
            f.seek(COMMENT_START)
            comment = f.read(COMMENT_LENGTH).decode("ascii").rstrip("\0")
            
            # Extract timestamp
            ts_match = re.search(r"(\d\d):(\d\d):(\d\d) (\d\d)/(\d\d)/(\d\d\d\d)", comment)
            if not ts_match:
                return None
                
            # Extract timezone
            tz_match = re.search(r"\(UTC(([-+])\d+)?:?(\d\d)?\)", comment)
            hrs = 0 if not tz_match or tz_match.group(1) is None else int(tz_match.group(1))
            mins = 0 if not tz_match or tz_match.group(3) is None else (
                -int(tz_match.group(3)) if tz_match.group(2) == '-' else int(tz_match.group(3))
            )
            
            # Extract battery and temperature
            battery_match = re.search(r"(\d+\.\d+)V", comment)
            temp_match = re.search(r"(-?\d+\.\d+)C", comment)
            sn_match = re.search(r"(................) at", comment)
            
            timestamp = datetime.strptime(ts_match.group(0), "%H:%M:%S %d/%m/%Y")
            timestamp = timestamp.replace(tzinfo=timezone(timedelta(hours=hrs, minutes=mins)))
            
            return {
                "timestamp": timestamp,
                "unix_time": date2unix(timestamp),
                "battery_v": float(battery_match.group(1)) if battery_match else None,
                "temperature_c": float(temp_match.group(1)) if temp_match else None,
                "serial_number": sn_match.group(1).strip() if sn_match else None,
                "timezone_offset_hours": hrs,
                "timezone_offset_mins": mins,
                "comment": comment,
            }
    except Exception as e:
        return None


def is_hydromoth_file(wav_path):
    """Check if a WAV file is from HydroMoth device."""
    metadata = extract_hydromoth_metadata(wav_path)
    return metadata is not None


def fromp(signal, ref, fs):
    """Calculate overall SPL from a pressure signal using HydroMoth formula."""
    P2 = np.power(np.abs(signal) / ref, 2)
    return 10.0 * np.log10(fs * np.nansum(P2) / len(signal))


def calculate_spl_from_pressure(signal, ref=1.0, fs=None):
    """Calculate overall SPL from pressure signal."""
    if fs is None:
        fs = 1.0
    return fromp(signal, ref, fs)


def calculate_spl_for_third_octave_bands(signal, ref, fd, fu, fs):
    """Calculate SPL for a specific third-octave band using Hanning-windowed FFT."""
    win = np.hanning(len(signal))
    XX = np.multiply(win, signal)
    fft_mag = np.abs(np.fft.fft(XX)) / np.sum(win)
    fft_freqs = np.fft.fftfreq(len(XX), 1.0 / fs)
    fft_mag = np.fft.fftshift(fft_mag)
    fft_freqs = np.fft.fftshift(fft_freqs)

    indices = np.argwhere((fft_freqs >= fd) & (fft_freqs <= fu))
    x_band = [fft_mag[idx[0]] for idx in indices]

    if len(x_band) == 0:
        return None, fft_mag[int(fs / 2):], fft_freqs[int(fs / 2):]

    Pfft = np.divide(x_band, ref)
    if len(x_band) == 1:
        spl = 10.0 * np.log10(2 * np.power(Pfft[0], 2) * (fs / len(signal)))
    else:
        spl = 10.0 * np.log10(2 * np.sum(np.power(Pfft, 2)) * (fs / len(signal)))

    return spl, fft_mag[int(fs / 2):], fft_freqs[int(fs / 2):]


def process_hydromoth_wav(wav_path, vpp=3.0, sensitivity_db=5.0, gain_db=0, ref=1.0):
    """
    Process a single HydroMoth WAV file.
    
    Args:
        wav_path: Path to WAV file
        vpp: Peak-to-peak voltage (default 3.0V for HydroMoth)
        sensitivity_db: Microphone sensitivity in dB used in the original HydroMoth script
        gain_db: Gain in dB
        ref: Reference pressure (1.0 for underwater)
    
    Returns:
        dict: Contains metadata, SPL data, and time series
    """
    metadata = extract_hydromoth_metadata(wav_path)
    if not metadata:
        return None
    
    # Read WAV file
    try:
        sample_rate, signal_data = wavfile.read(wav_path)
    except Exception as e:
        return None
    
    # Determine bit depth
    if signal_data.dtype == np.int16:
        cte = 2 ** 15
    elif signal_data.dtype == np.int32:
        cte = 2 ** 31
    else:
        cte = 1.0
    
    fs = int(sample_rate)
    duration = len(signal_data) / fs
    
    # Convert to pressure signal
    pressure_signal = []
    for value in signal_data:
        if value >= cte:
            value = value - (2 * cte)
        elif value <= -cte:
            value = value + (2 * cte)
        
        # Convert to pressure in µPa
        p_micropa = (vpp * 10**6 * value) / (cte * np.power(10.0, sensitivity_db / 10.0) * np.power(10.0, gain_db / 10.0))
        pressure_signal.append(p_micropa)
    
    pressure_signal = np.array(pressure_signal)
    
    # Calculate overall SPL
    spl_overall = calculate_spl_from_pressure(pressure_signal, ref, fs)
    
    # Calculate SPL for third-octave bands
    bands = {
        "63Hz": (56.3, 70.8),
        "125Hz": (112, 141),
        "2kHz": (1778, 2239),
    }
    
    spl_bands = {}
    for band_name, (fd, fu) in bands.items():
        spl, _, _ = calculate_spl_for_third_octave_bands(pressure_signal, ref, fd, fu, fs)
        if spl is not None:
            spl_bands[band_name] = spl
    
    return {
        "wav_file": os.path.basename(wav_path),
        "wav_path": wav_path,
        "metadata": metadata,
        "sample_rate": fs,
        "duration_seconds": duration,
        "spl_overall_db": spl_overall,
        "spl_bands": spl_bands,
        "signal": pressure_signal,
    }

def process_hydromoth_folder(folder_path, vpp=3.0, sensitivity_db=5.0, gain_db=0,
                              window_seconds=5.0, ref=1.0):
    import glob
    
    wav_files = sorted(glob.glob(os.path.join(folder_path, "*.wav")))
    results = []
    
    for wav_file in wav_files:
        result = process_hydromoth_wav(wav_file, vpp, sensitivity_db, gain_db, ref)
        if result:
            signal = result["signal"]
            fs = result["sample_rate"]
            metadata = result["metadata"]

            # ✅ timestamp inicio absoluto
            start_timestamp = metadata["timestamp"].timestamp()

            window_samples = int(window_seconds * fs)

            times = []
            overall_levels = []
            levels_63 = []
            levels_125 = []
            levels_2k = []

            for i in range(0, len(signal) - window_samples, window_samples):
                window_signal = signal[i:i + window_samples]

                overall_spl = calculate_spl_from_pressure(window_signal, ref, fs)
                spl63, _, _ = calculate_spl_for_third_octave_bands(window_signal, ref, 56.3, 70.8, fs)
                spl125, _, _ = calculate_spl_for_third_octave_bands(window_signal, ref, 112, 141, fs)
                spl2k, _, _ = calculate_spl_for_third_octave_bands(window_signal, ref, 1778, 2239, fs)

                # ✅ tiempo absoluto
                time_s = i / fs
                abs_time = start_timestamp + time_s

                times.append(abs_time)
                overall_levels.append(overall_spl)
                levels_63.append(spl63)
                levels_125.append(spl125)
                levels_2k.append(spl2k)

            result["time_series"] = {
                "times": np.array(times),
                "overall_levels": np.array(overall_levels),
                "band_levels": {
                    "63Hz": np.array(levels_63),
                    "125Hz": np.array(levels_125),
                    "2kHz": np.array(levels_2k),
                },
                "time_type": "absolute",  # ✅ útil para el plot
            }

            results.append(result)

    return results
def process_hydromoth_folderold(folder_path, vpp=3.0, sensitivity_db=5.0, gain_db=0, 
                              window_seconds=5.0, ref=1.0):
    """
    Process all HydroMoth WAV files in a folder.
    
    Args:
        folder_path: Path to folder containing WAV files
        vpp: Peak-to-peak voltage
        sensitivity_db: Microphone sensitivity used in the original HydroMoth script
        gain_db: Gain in dB
        window_seconds: Time window for SPL calculation
        ref: Reference pressure
    
    Returns:
        list: List of processing results with metadata
    """
    import glob
    
    wav_files = sorted(glob.glob(os.path.join(folder_path, "*.wav")))
    results = []
    
    for wav_file in wav_files:
        result = process_hydromoth_wav(wav_file, vpp, sensitivity_db, gain_db, ref)
        if result:
                signal = result["signal"]
                fs = result["sample_rate"]
                window_samples = int(window_seconds * fs)

                times = []
                overall_levels = []
                levels_63 = []
                levels_125 = []
                levels_2k = []

                for i in range(0, len(signal) - window_samples, window_samples):
                    window_signal = signal[i:i + window_samples]
                    overall_spl = calculate_spl_from_pressure(window_signal, ref, fs)
                    spl63, _, _ = calculate_spl_for_third_octave_bands(window_signal, ref, 56.3, 70.8, fs)
                    spl125, _, _ = calculate_spl_for_third_octave_bands(window_signal, ref, 112, 141, fs)
                    spl2k, _, _ = calculate_spl_for_third_octave_bands(window_signal, ref, 1778, 2239, fs)


                    start_timestamp = result["metadata"]["timestamp"]

                    time_s = i / fs
                    times.append(time_s)
                    abs_time = start_timestamp.timestamp() + time_s
                    times.append(abs_time)

                    overall_levels.append(overall_spl)
                    levels_63.append(spl63)
                    levels_125.append(spl125)
                    levels_2k.append(spl2k)

                result["time_series"] = {
                    "times": np.array(times),
                    "overall_levels": np.array(overall_levels),
                    "band_levels": {
                        "63Hz": np.array(levels_63),
                        "125Hz": np.array(levels_125),
                        "2kHz": np.array(levels_2k),
                    },
                }
                if levels_63 and levels_125 and levels_2k:
                    result["spl_bands"] = {
                        "63Hz": float(np.nanmean(levels_63)),
                        "125Hz": float(np.nanmean(levels_125)),
                        "2kHz": float(np.nanmean(levels_2k)),
                    }
                results.append(result)

    return results
