##############script creatred by Albert Garcia-Benadí
##############ORCID:     0000-0002-5560-4392
##############The function is read wav generated by Hydromoth  (https://www.openacousticdevices.info/applications)
##############v1 createds 08 of june 2026
import numpy as np
import matplotlib.pyplot as plt
import wave
import os.path

import glob

from pylab import *

import calendar
import datetime
from datetime import datetime,date,timezone, timedelta
import datetime as dt

from scipy.io import wavfile
from scipy import fft
import matplotlib.dates as mdates
import pandas as pd





def date2unix(date):
    return calendar.timegm(date.timetuple())
def unix2date(unix):
    return datetime.utcfromtimestamp(unix)



##Function to calculate the SPL for all frequencies
def FromP(Signal,ref,fs):
    n=1
##    vect=[]
##    for i in Signal:
##        if np.isnan(i):
##            vect.append(np.nan)
##        else:
##            vect.append(np.power(np.abs(i)/ref,2))
            
    P2=(np.power(np.abs(Signal)/ref,2))
    
    SPL=10.*np.log10(fs*np.nansum(P2)/(len(Signal)))
    return SPL

def SPLforbandwithHanning(Signal,ref,fd63,fu63,fd125,fu125,fd2k,fu2k,fs): 
    
    win=np.hanning(len(Signal))
    x63H=[]
    x125H=[]
    x2kH=[]
    XX=np.multiply(win,Signal)
    rfqX4=np.abs(np.fft.fft(XX))/(np.sum(win))
    FrqX=np.fft.fftfreq(len(XX), 1.0/fs)
    rfqX4=np.fft.fftshift(rfqX4)
    FrqX=np.fft.fftshift(FrqX)
##    print('FrqX',FrqX)
    Ind63X=np.argwhere((FrqX>=fd63) & (FrqX<=fu63))
    Ind125X=np.argwhere((FrqX>=fd125) & (FrqX<=fu125))
    Ind2kX=np.argwhere((FrqX>=fd2k) & (FrqX<=fu2k))

    for m in range(len(Ind63X)):x63H.append(rfqX4[Ind63X[m]])
    for m in range(len(Ind125X)):x125H.append(rfqX4[Ind125X[m]])
    for m in range(len(Ind2kX)):x2kH.append(rfqX4[Ind2kX[m]])

    Pfft63=np.divide(x63H,ref) 
    Pfft125=np.divide(x125H,ref)
    Pfft2k=np.divide(x2kH,ref) 

    if len(x63H)==1:
        SPL63=10.*np.log10(2*np.power(Pfft63[0],2)*(fs/len(Signal)))
    else:
        SPL63=10.*np.log10(2*np.sum(np.power(Pfft63,2))*(fs/len(Signal)))

    if len(x125H)==1:
        SPL125=10.*np.log10(2*np.power(Pfft125[0],2)*(fs/len(Signal)))
    else:
        SPL125=10.*np.log10(2*np.sum(np.power(Pfft125,2))*(fs/len(Signal)))

    if len(x2kH)==1:
        SPL2k=10.*np.log10(2*np.power(Pfft2k[0],2)*(fs/len(Signal)))
    else:
        SPL2k=10.*np.log10(2*np.sum(np.power(Pfft2k,2))*(fs/len(Signal)))

    return SPL63,SPL125,SPL2k,2.*rfqX4[int(fs/2):],FrqX[int(fs/2):]




##CONFIGURATION PARAMETER   Define the interval of the frequency band in a 1/3 octave
down63=56.3
up63=70.8
down125=112
up125=141
down2k=1778
up2k=2239
ref=1.#the underwater reference pressure is 10^-6Pa but the units of the pressure are 10^-6Pa, so the value is 1
Gain=0 #db corresnpoindece as 1 Av###
Sensi=5.#Amb 5 dB la senyal de ñ'Obsea i del huydrosmoot son semblants...-38.# dB µV/µPa data from--> https://github.com/OpenAcousticDevices/Datasheets/blob/main/HydroMoth_1_0_1_Datasheet/HydroMoth_1_0_1_Datasheet.pdf
Vpp=3.#V
Int_Time=5.#temps d'integració



##############asking where are the wav files


print('Insert the path where is the wavfile')
Root_In=input()


##########FIND ALL WAV FILES

dir_wav=glob.glob(Root_In+'/'+'*.wav')
dircf=np.sort(dir_wav)


########SIZE FROM COMMENTS I WAV FILE
COMMENT_START = 0x38
COMMENT_LENGTH = 0x180



print('Number of wav files found '+str(len(dircf)))

##########REad each wav file

for i in dircf:
    print(i)
    

    with open(i, "rb") as f:

        f.seek(COMMENT_START)

        comment = f.read(COMMENT_LENGTH).decode("ascii").rstrip("\0")

            # Read the time and timezone from the header

        ts = re.search(r"(\d\d:\d\d:\d\d \d\d/\d\d/\d\d\d\d)", comment)[1]

        tz = re.search(r"\(UTC(([-|+])\d+)?:?(\d\d)?\)", comment)

        hrs = 0 if tz[1] is None else int(tz[1])

        mins = 0 if tz[3] is None else -int(tz[3]) if '-' in tz[2] else int(tz[3])

        timestamp = datetime.strptime(ts, "%H:%M:%S %d/%m/%Y")
              
        timestamp = timestamp.replace(tzinfo=timezone(timedelta(hours=hrs, minutes=mins)))

            # Read the battery voltage and temperature from the header

        battery = re.search(r"(\d\.\d)V", comment)[1]

        temperature = re.search(r"(-?\d+\.\d)C", comment)[1]
        SN = re.search(r"(................) at", comment)[1]

##    print('temp ',temperature,timestamp,' battery ',battery,date2unix(timestamp))

    dat=date2unix(timestamp)#hora inicio en formato unix

    
    samplingFrequency, signalData = wavfile.read(i)
    if signalData.dtype==int16:
        cte=2**(16-1)
    if signalData.dtype==int32:
        cte=2**(32-1)
    Fs=int(samplingFrequency)

    t=np.arange(dat,dat+len(signalData)/Fs,1/Fs)

    Xti=np.array([unix2date(t[i]) for i in range(len(t))])
    xfmt = mdates.DateFormatter('%H:%M:%S') #format de l'eix x
    xfmt_t = mdates.DateFormatter('%H:%M:%S') #format de l'eix x
    Txfmt=str(unix2date(t[0]))#format de la finestra


    Title_time=unix2date(t[0]).strftime('%d - %m - %Y')
    Title_plot=unix2date(t[0]).strftime('%Y%m%d-%H%M')


##    print('frequency sampling ',Fs,' Hz duration of file '+str(round(len(signalData)/Fs,1))+' seconds')
    vect_P=[];vect_pres=[]
    for j in signalData:
        value=j
        if value>=cte:
            value=value-2
        if value<=-1.*cte:
            value=value[i]+2
    

        vect_pres.append(Vpp*(10**6)*value/(cte*np.power(10.,Sensi/10.)*np.power(10.,Gain/10.)))##aquest és el vector pressio, suposem que el Gain=0
            

    matrix=[];Spl_63=[];Spl_125=[];Spl_2k=[];SPL=[];Time_p=[]
    for j in range(int(len(vect_pres)/Fs)):###loop per la imatge general
        ini=int(Fs*j)
        fi=int((j+1)*Fs)
        Time_p.append(t[int(Fs*j)])
        vector=vect_pres[ini:fi]

        SPL.append(FromP(vector,ref,Fs))
        spl63,spl125,spl2k,FFT,eje_Freq=SPLforbandwithHanning(vector,ref,down63,up63,down125,up125,down2k,up2k,Fs)
##        print('All in dB -- 63 Hz ',spl63,'125 Hz ',spl125,'2 kHz ',spl2k)
        Spl_63.append(spl63)
        Spl_125.append(spl125)
        Spl_2k.append(spl2k)
        eix_Y=np.copy(eje_Freq)
##        print('eix correcte',eje_Freq,len(eje_Freq))
##        print('senyal',FFT,len(FFT))
        if len(matrix)==0:
            matrix=np.copy(FFT)
        else:
            matrix=np.vstack((matrix,FFT))


    Spl_63_csv=[];Spl_125_csv=[];Spl_2k_csv=[];SPL_csv=[];Time_csv=[]
    for j in range(int(len(vect_pres)/(Int_Time*Fs))):###loop pel csv
        ini=int(Int_Time*Fs*j)
        fi=int((j+1)*Int_Time*Fs)
        Time_csv.append(int(t[int(Int_Time*Fs*j)]))
        vector=vect_pres[ini:fi]

        SPL_csv.append(round(FromP(vector,ref,Fs),2))
        spl63,spl125,spl2k,FFT,eje_Freq=SPLforbandwithHanning(vector,ref,down63,up63,down125,up125,down2k,up2k,Fs)

        Spl_63_csv.append(round(spl63,2))
        Spl_125_csv.append(round(spl125,2))
        Spl_2k_csv.append(round(spl2k,2))

##########PASAR DADES A CSV
    data_1={'Unix Time UTC':Time_csv,
          
          'SPL at 63 Hz [dB]':Spl_63_csv
          }
    data_2={'Unix Time UTC':Time_csv,
          
          
          'SPL at 125 Hz [dB]':Spl_125_csv}
    data_3={'Unix Time UTC':Time_csv,
          'SPL at 2k Hz [dB]':Spl_2k_csv}
    
    data_4={'Unix Time UTC':Time_csv,
          'SPL [dB]':SPL_csv,
          }
    data_0={'Unix Time UTC':Time_csv,
          'SPL [dB]':SPL_csv,
          'SPL at 63 Hz [dB]':Spl_63_csv,
          'SPL at 125 Hz [dB]':Spl_125_csv,
          'SPL at 2k Hz [dB]':Spl_2k_csv}

    df_0 = pd.DataFrame(data_0)
    df_1 = pd.DataFrame(data_1)
    df_2 = pd.DataFrame(data_2)
    df_3 = pd.DataFrame(data_3)
    df_4 = pd.DataFrame(data_4)

    ID=SN#pendent d'obtenir del wav

    FileName_0=Root_In+str(ID)+'-All.csv'
    FileName_1=Root_In+str(ID)+'-63Hz.csv'
    FileName_2=Root_In+str(ID)+'-125Hz.csv'
    FileName_3=Root_In+str(ID)+'-2kHz.csv'
    FileName_4=Root_In+str(ID)+'-full.csv'

    
    if os.path.isfile(FileName_0):
        
        df_0.to_csv(FileName_0,mode='a',header=False,sep=',',index=False)
    else:
        df_0.to_csv(FileName_0,sep=',',index=False)


    if os.path.isfile(FileName_1):
        
        df_1.to_csv(FileName_1,mode='a',header=False,sep=',',index=False)
    else:
        df_1.to_csv(FileName_1,sep=',',index=False)

    if os.path.isfile(FileName_2):
        
        df_2.to_csv(FileName_2,mode='a',header=False,sep=',',index=False)
    else:
        df_2.to_csv(FileName_2,sep=',',index=False)

        
    if os.path.isfile(FileName_3):
        
        df_3.to_csv(FileName_3,mode='a',header=False,sep=',',index=False)
    else:
        df_3.to_csv(FileName_3,sep=',',index=False)
        
    if os.path.isfile(FileName_4):
        
        df_4.to_csv(FileName_4,mode='a',header=False,sep=',',index=False)
    else:
        df_4.to_csv(FileName_4,sep=',',index=False)
        
##############LA TRAMESA D'ARXIUS JA HA ACABAT, generem plots
    
    Xti_1=np.array([unix2date(Time_p[i]) for i in range(len(Time_p))])
    xfmt_1 = mdates.DateFormatter('%H:%M:%S') #format de l'eix x
    
    Txfmt_1=str(unix2date(t[0]))#format de la finestra

    fig=plt.figure(figsize=(20,15))
    ax3=plt.subplot(311)
    ax3.plot(Xti,signalData/cte)
    ax3.xaxis.set_major_formatter(xfmt)
    ax3.set_ylabel('Pressure Signal normalized')
    ax3.set_xlim(Xti[0],Xti[-1])
    ax3.grid()
    plt.suptitle(str(temperature)+' Celsius and battery in '+str(battery)+' V')
    
    ax1=plt.subplot(312)
    ax1.plot(Xti_1,SPL,'k',label='Full', alpha=.7)
    ax1.plot(Xti_1,Spl_63,'b',label='63 Hz', alpha=.7)
    ax1.plot(Xti_1,Spl_125,'r',label='125 Hz', alpha=.7)
    ax1.plot(Xti_1,Spl_2k,'g',label='2 kHz', alpha=.7)
    ax1.set_ylabel('Sound pressure level [dB]')
    ax1.xaxis.set_major_formatter(xfmt_1)
    ax1.set_xlim(Xti[0],Xti[-1])
    ax1.legend(loc='best')
    ax1.grid()
##    plt.show()


    matrix_1=matrix.T
    matrix_C=matrix_1[::-1]

    
    times_num = mdates.date2num([unix2date(t[0]),unix2date(t[-1])])
    extentPlot = [(times_num[0]), (times_num[1]), eix_Y[0], (eix_Y[-1])]
    
    ax2= plt.subplot(313)

    im2=ax2.imshow(matrix_C,cmap='ocean',  aspect='auto',extent=extentPlot)#interpolation='gaussian',
    ax2.xaxis.set_major_formatter(xfmt)
    ax2.set_xlim(Xti[0],Xti[-1])
    ax2.grid()
    ax2.set_ylabel('Frequency [Hz]')
    plt.suptitle('Day: '+Title_time+' - Temperature: '+str(temperature)+' Celsius - Battery level: '+str(battery)+' V')
    plt.savefig(Root_In+'/'+str(ID)+'-'+str(Title_plot)+'-v1.png',dpi=200)  #############aquí fiques on vols l'arxiu
    plt.close()
                   
##    plt.plot(matrix)
##    plt.show()
##        

        



   


